library(chromote)
b <- ChromoteSession$new()
b$Log$enable()
b$Log$entryAdded(function(msg) {
  cat("CONSOLE: ", msg$text, "\n")
})
url <- paste0("file:///", normalizePath("repro.html", winslash = "/"))
b$Page$navigate(url)
Sys.sleep(5)
res <- b$Runtime$evaluate("!!document.getElementById('plot1')._tracesToCSV", returnByValue = TRUE)
cat("Decorated: ", res$result$value, "\n")
b$close()
